name: Example

on:
  push:
    branches:
      - main
      - v1
    paths:
      - "apps/example/**"
      - "packages/cli/**"
      - "packages/core/**"
      - "packages/server/**"
      - "packages/react/**"
      - "package.json"
      - "pnpm-workspace.yaml"
      - ".github/workflows/example.yml"
      - ".github/actions/example-setup/**"
  pull_request:
    branches:
      - main
      - v1
    paths:
      - "apps/example/**"
      - "packages/cli/**"
      - "packages/core/**"
      - "packages/server/**"
      - "packages/react/**"
      - "package.json"
      - "pnpm-workspace.yaml"
      - ".github/workflows/example.yml"
      - ".github/actions/example-setup/**"

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/example-setup
      - run: pnpm format
      - run: pnpm --filter example format

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/example-setup
      - run: pnpm --filter example typecheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/example-setup
      - run: pnpm --filter example lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/example-setup
      - run: pnpm --filter example build
